const listData = {
    "New Cars": [
      "Toyota",
      "Honda",
      "Ford",
      "Chevrolet",
      "Nissan",
      "Volkswagen",
      "Mazda",
      "Subaru",
      "Kia",
      "Hyundai",
    ],
    "Sell Car": [
      "Used Car",
      "Used Car Valuation",
      "Instant Cash Offer",
      "Trade-In Program",
      "Sell to Dealer",
      "Sell for Parts",
    ],
    "Buy Cars": [
      "BMW",
      "Audi",
      "Mercedes",
      "Lexus",
      "Porsche",
      "Jaguar",
      "Volvo",
      "Land Rover",
      "Infiniti",
      "Acura",
    ],
    "Car Service": [
      "Detailing",
      "Tire Change",
      "Battery Check",
      "Paint Touch-Up",
      "Windshield Repair",
      "Interior Cleaning",
      "Rust Protection",
      "Brake Inspection",
      "Suspension Check",
    ],
  };

  export default listData;